version: "3.9"

services:
  redis:
    container_name: redis_GESIS
    image: redis:7.0.11-alpine

  app:
    container_name: app_GESIS
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - DJANGO_DEBUG=1
    depends_on:
      - redis
      - db

  celery:
    container_name: celery_GESIS
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: >
      sh -c "celery -A app worker --loglevel=info"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - DJANGO_DEBUG=1
    depends_on:
      - redis
      - db

  db:
    container_name: db_GESIS
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin_GESIS
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - db

volumes:
  postgres_data:
