# Generated by Django 4.2.7 on 2025-07-30 09:02

import uuid

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_number", models.CharField(default="0", max_length=32)),
                ("category_score", models.FloatField()),
                ("category_parent", models.CharField(max_length=32)),
                ("category_label", models.CharField(max_length=32)),
                ("category_confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criteria_classification", models.CharField(max_length=32)),
                ("criteria_window", models.BooleanField()),
                ("criteria_tab", models.BooleanField()),
                ("criteria_domain", models.BooleanField()),
                ("criteria_click", models.BooleanField()),
                ("criteria_scroll", models.BooleanField()),
                ("snapshot_html", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain_title", models.CharField()),
                ("snapshot_html", models.TextField(blank=True)),
                ("domain_status", models.CharField()),
                ("domain_fav_icon", models.CharField()),
                ("domain_session_id", models.CharField(blank=True)),
                (
                    "start_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "closing_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("domain_url", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category_number", models.CharField(default="0", max_length=32)),
                (
                    "criteria_classification",
                    models.CharField(default="full_allow", max_length=32),
                ),
                ("category_label", models.CharField(default="0", max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("global_session_id", models.CharField(max_length=255, unique=True)),
                ("start_time", models.DateTimeField()),
                ("closing_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Window",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True)),
                ("closing_time", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("window_num", models.CharField(max_length=32)),
                ("window_session_id", models.CharField(blank=True, max_length=255)),
                (
                    "global_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows",
                        to="core.globalsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("wave_status", models.CharField(max_length=32)),
                ("wave_type", models.CharField(max_length=32)),
                ("wave_number", models.CharField(max_length=32)),
                ("client_id", models.CharField(max_length=32)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True)),
                ("closing_time", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("window_num", models.CharField(max_length=32)),
                ("tab_num", models.CharField(max_length=32)),
                ("tab_session_id", models.CharField(blank=True, max_length=255)),
                ("domains", models.ManyToManyField(to="core.domain")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="core.window",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scroll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scroll_time", models.DateTimeField(blank=True)),
                ("scroll_x", models.FloatField()),
                ("scroll_y", models.FloatField()),
                ("page_x_offset", models.FloatField()),
                ("page_y_offset", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrolls",
                        to="core.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("privacy_mode", models.BooleanField(default=False)),
                (
                    "privacy_start_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "privacy_end_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hosts_version", models.CharField(default="0", max_length=32)),
                (
                    "categories",
                    models.ManyToManyField(related_name="hosts", to="core.category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPrivacy",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("privacy_mode", models.BooleanField(default=False)),
                (
                    "privacy_start_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "privacy_end_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical privacy",
                "verbose_name_plural": "historical privacys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("extension_version", models.CharField(blank=True, max_length=32)),
                ("extension_installed_at", models.DateTimeField(blank=True, null=True)),
                ("extension_updated_at", models.DateTimeField(blank=True, null=True)),
                ("extension_browser", models.CharField(blank=True, max_length=128)),
                ("extension_data_collection", models.BooleanField(default=True)),
                ("host_version", models.CharField(default="0", max_length=32)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical extension",
                "verbose_name_plural": "historical extensions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Extension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("extension_version", models.CharField(blank=True, max_length=32)),
                ("extension_installed_at", models.DateTimeField(blank=True, null=True)),
                ("extension_updated_at", models.DateTimeField(blank=True, null=True)),
                ("extension_browser", models.CharField(blank=True, max_length=128)),
                ("extension_data_collection", models.BooleanField(default=True)),
                ("host_version", models.CharField(default="0", max_length=32)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("click_time", models.DateTimeField(blank=True)),
                ("click_type", models.CharField(max_length=32)),
                ("click_target_element", models.CharField(default="0")),
                ("click_target_tag", models.CharField(default="0")),
                ("click_target_id", models.CharField(default="0")),
                ("click_target_class", models.CharField(default="0")),
                ("click_page_x", models.FloatField(default=0)),
                ("click_page_y", models.FloatField(default=0)),
                ("click_referrer", models.CharField(default="0")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="core.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="criteria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.criteria",
            ),
        ),
        migrations.AddConstraint(
            model_name="window",
            constraint=models.UniqueConstraint(
                fields=("window_num", "window_session_id", "start_time"),
                name="unique_window_in_global_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                fields=("tab_num", "tab_session_id", "start_time"),
                name="unique_tab_in_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                fields=("domain_title", "domain_url", "start_time"),
                name="unique_domain_in_tab",
            ),
        ),
    ]
