# Generated by Django 4.2.7 on 2025-09-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="window",
            name="window_num",
            field=models.IntegerField(),
        ),
    ]
