# Generated by Django 4.2.7 on 2024-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wave",
            old_name="clent_id",
            new_name="client_id",
        ),
    ]
