# Generated by Django 4.2.7 on 2023-11-13 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client_id", models.CharField(max_length=32)),
                ("wave_number", models.IntegerField()),
                ("wave_name", models.CharField(max_length=32)),
                ("wave_type", models.CharField(max_length=32)),
                ("wave_status", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="WaveParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addtional_field", models.CharField(max_length=32)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.wave"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wave",
            name="participants",
            field=models.ManyToManyField(
                through="core.WaveParticipant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
