# Generated by Django 4.2.7 on 2023-11-14 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_wave_waveparticipant_wave_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waveparticipant",
            old_name="addtional_field",
            new_name="additional_field",
        ),
    ]
