# Generated by Django 4.2.7 on 2024-02-11 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_wave_users_user_waves"),
    ]

    operations = [
        migrations.AddField(
            model_name="wave",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
