# Generated by Django 4.2.7 on 2025-09-02 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_window_window_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain",
            old_name="domain_status",
            new_name="domain_last_accessed",
        ),
    ]
