# Generated by Django 4.2.7 on 2024-02-10 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_wave_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="waves",
        ),
        migrations.AddField(
            model_name="wave",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
