# Generated by Django 4.2.7 on 2024-02-19 15:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_clent_id_wave_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="window",
            name="window_num",
            field=models.CharField(max_length=32),
        ),
    ]
