# Generated by Django 4.2.7 on 2025-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_domain_status_domain_domain_last_accessed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain_fav_icon",
            field=models.CharField(blank=True),
        ),
    ]
