# Generated by Django 4.2.7 on 2024-02-11 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_wave_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="waves",
        ),
    ]
