# Generated by Django 4.2.7 on 2024-02-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_user_waves"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wave",
            name="users",
        ),
        migrations.AddField(
            model_name="user",
            name="waves",
            field=models.ManyToManyField(to="core.wave"),
        ),
    ]
