# Generated by Django 4.2.7 on 2024-02-16 21:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="domains",
            field=models.ManyToManyField(to="core.domain"),
        ),
    ]
