# Generated by Django 4.2.7 on 2025-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_domain_domain_fav_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="scroll",
            name="scroll_metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
