# Generated by Django 4.2.7 on 2024-02-19 15:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab",
            name="tab_id",
            field=models.CharField(max_length=32),
        ),
    ]
