# Generated by Django 4.2.7 on 2024-02-19 15:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_tab_tab_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain_title", models.CharField(max_length=32)),
                ("domain_url", models.CharField(max_length=32)),
                ("domain_fav_icon", models.CharField(max_length=32)),
                ("domain_status", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tab",
            name="domains",
            field=models.ManyToManyField(to="core.domain"),
        ),
    ]
