# Generated by Django 4.2.7 on 2026-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_scroll_scroll_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[("llm", "LLM"), ("social", "Social")], max_length=32
                    ),
                ),
                ("provider", models.CharField(max_length=32, unique=True)),
                ("version", models.CharField(max_length=32)),
                ("hostname_patterns", models.JSONField(blank=True, default=list)),
                ("selectors", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="extension",
            name="selector_version",
            field=models.CharField(default="0", max_length=32),
        ),
        migrations.AddField(
            model_name="historicalextension",
            name="selector_version",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
