# Generated by Django 4.2.7 on 2024-02-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_wave_start_date_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wave",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
