# Generated by Django 4.2.7 on 2024-02-17 20:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_click"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scroll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scroll_time", models.DateTimeField(blank=True)),
                ("scroll_x", models.IntegerField()),
                ("scroll_y", models.IntegerField()),
                ("page_x_offset", models.IntegerField()),
                ("page_y_offset", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrolls",
                        to="core.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
