# Generated by Django 4.2.7 on 2024-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_wave_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="window",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
