# Generated by Django 4.2.7 on 2024-02-19 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_scroll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tab",
            name="window",
        ),
    ]
