# Generated by Django 4.2.7 on 2024-02-13 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_window_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="waves",
        ),
    ]
