# Generated by Django 4.2.7 on 2024-02-19 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_tab_window"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tab",
            old_name="tab_id",
            new_name="tab_num",
        ),
    ]
