# Generated by Django 4.2.7 on 2024-02-15 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_user_waves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="window",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
