# Generated by Django 4.2.7 on 2024-03-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_tab_id_tab_tab_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain_fav_icon",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain_status",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain_title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="domain",
            name="domain_url",
            field=models.CharField(),
        ),
    ]
