# Generated by Django 4.2.7 on 2024-03-06 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_domain_domain_fav_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="closing_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="domain",
            name="start_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
