# Generated by Django 4.2.7 on 2024-03-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_domain_closing_time_domain_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="snapshot_html",
            field=models.TextField(blank=True),
        ),
    ]
