# Generated by Django 4.2.7 on 2024-03-06 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_domain_snapshot_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tab",
            name="snapshot_html",
        ),
    ]
