# Generated by Django 4.2.7 on 2024-03-19 19:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_tab_snapshot_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_score", models.FloatField()),
                ("category_parent", models.CharField(max_length=32)),
                ("category_label", models.CharField(max_length=32)),
                ("category_confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criteria_classification", models.CharField(max_length=32)),
                ("criteria_window", models.BooleanField()),
                ("criteria_tab", models.BooleanField()),
                ("criteria_domain", models.BooleanField()),
                ("criteria_click", models.BooleanField()),
                ("criteria_scroll", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
