# Generated by Django 4.2.7 on 2024-03-19 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_category_criteria_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="hostname",
            new_name="url_hostname",
        ),
    ]
