# Generated by Django 4.2.7 on 2024-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_category_criteria_host_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="hostname",
            field=models.CharField(max_length=32),
        ),
    ]
