# Generated by Django 4.2.7 on 2024-03-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_host_hostname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="criteria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.criteria",
            ),
        ),
    ]
