# Generated by Django 4.2.7 on 2024-03-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_category_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_number",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
