# Generated by Django 4.2.7 on 2024-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_category_category_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="snapshot_html",
            field=models.BooleanField(default=False),
        ),
    ]
