# Generated by Django 4.2.7 on 2024-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_criteria_snapshot_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="category_label",
            field=models.CharField(default="0", max_length=32),
        ),
        migrations.AddField(
            model_name="domain",
            name="category_number",
            field=models.CharField(default="0", max_length=32),
        ),
        migrations.AddField(
            model_name="domain",
            name="criteria_classification",
            field=models.CharField(default="full_allow", max_length=32),
        ),
    ]
