# Generated by Django 4.2.7 on 2024-03-27 22:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_domain_category_label_domain_category_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("privacy_mode", models.BooleanField(default=False)),
                ("privacy_start_time", models.DateTimeField(blank=True)),
                ("privacy_end_time", models.DateTimeField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
