# Generated by Django 4.2.7 on 2024-03-28 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_extension_created_at_alter_extension_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="extension_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historicalextension",
            name="extension_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
