# Generated by Django 4.2.7 on 2024-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_extension_extension_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="extension_updated_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_updated_at",
            field=models.DateTimeField(),
        ),
    ]
