# Generated by Django 4.2.7 on 2024-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_extension_extension_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scroll",
            name="page_x_offset",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="scroll",
            name="page_y_offset",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="scroll",
            name="scroll_x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="scroll",
            name="scroll_y",
            field=models.FloatField(),
        ),
    ]
