# Generated by Django 4.2.7 on 2024-03-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_scroll_page_x_offset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="click",
            name="click_location",
        ),
        migrations.AddField(
            model_name="click",
            name="click_page_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="click",
            name="click_page_y",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="click",
            name="click_referrer",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="click",
            name="click_target_class",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="click",
            name="click_target_element",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="click",
            name="click_target_id",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="click",
            name="click_target_tag",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
