# Generated by Django 4.2.7 on 2024-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_remove_click_click_location_click_click_page_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="click_referrer",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_class",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_id",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_tag",
            field=models.CharField(default="0", max_length=200),
        ),
    ]
