# Generated by Django 4.2.7 on 2024-03-30 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_click_click_referrer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprivacy",
            name="privacy_end_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalprivacy",
            name="privacy_start_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="privacy_end_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="privacy",
            name="privacy_start_time",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
