# Generated by Django 4.2.7 on 2024-03-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_historicalprivacy_privacy_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="extension_browser",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="extension",
            name="extension_installed_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="extension",
            name="extension_updated_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="extension",
            name="extension_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_browser",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_installed_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_updated_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_version",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
