# Generated by Django 4.2.7 on 2024-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_extension_extension_browser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="extension_installed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extension",
            name="extension_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_installed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalextension",
            name="extension_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
