# Generated by Django 4.2.7 on 2024-04-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_extension_extension_installed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="version",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
