# Generated by Django 4.2.7 on 2024-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_host_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="host_version",
            field=models.CharField(default="0", max_length=32),
        ),
        migrations.AddField(
            model_name="historicalextension",
            name="host_version",
            field=models.CharField(default="0", max_length=32),
        ),
    ]
