# Generated by Django 4.2.7 on 2024-04-15 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_extension_host_version_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="host",
            old_name="version",
            new_name="hosts_version",
        ),
    ]
