# Generated by Django 4.2.7 on 2025-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_rename_version_host_hosts_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="click_referrer",
            field=models.CharField(default="0"),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_class",
            field=models.CharField(default="0"),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_element",
            field=models.CharField(default="0"),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_id",
            field=models.CharField(default="0"),
        ),
        migrations.AlterField(
            model_name="click",
            name="click_target_tag",
            field=models.CharField(default="0"),
        ),
    ]
