# Generated by Django 4.2.7 on 2025-03-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_click_click_referrer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="extension_data_collection",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalextension",
            name="extension_data_collection",
            field=models.BooleanField(default=True),
        ),
    ]
