input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
    if [message] =~ /^{.*}$/ {
        json {
            source => "message"
        }
    }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
